## Switches
set_property PACKAGE_PIN V17 [get_ports {A[0]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {A[0]}]
set_property PACKAGE_PIN V16 [get_ports {A[1]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {A[1]}]
set_property PACKAGE_PIN W16 [get_ports {A[2]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {A[2]}]
set_property PACKAGE_PIN W17 [get_ports {A[3]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {A[3]}]
set_property PACKAGE_PIN W15 [get_ports {A[4]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {A[4]}]
set_property PACKAGE_PIN V15 [get_ports {B[0]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {B[0]}]
set_property PACKAGE_PIN W14 [get_ports {B[1]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {B[1]}]
set_property PACKAGE_PIN W13 [get_ports {B[2]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {B[2]}]
set_property PACKAGE_PIN V2 [get_ports {B[3]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {B[3]}]
set_property PACKAGE_PIN T3 [get_ports {B[4]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {B[4]}]
set_property PACKAGE_PIN T2 [get_ports {ALUControl[0]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {ALUControl[0]}]
set_property PACKAGE_PIN R3 [get_ports {ALUControl[1]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {ALUControl[1]}]
set_property PACKAGE_PIN W2 [get_ports {ALUControl[2]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {ALUControl[2]}]
set_property PACKAGE_PIN U1 [get_ports {bshift[0]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {bshift[0]}]
set_property PACKAGE_PIN T1 [get_ports {bshift[1]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {bshift[1]}]
set_property PACKAGE_PIN R2 [get_ports dir]                    
    set_property IOSTANDARD LVCMOS33 [get_ports dir]
 

## LEDs
set_property PACKAGE_PIN U16 [get_ports {Result[0]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {Result[0]}]
set_property PACKAGE_PIN E19 [get_ports {Result[1]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {Result[1]}]
set_property PACKAGE_PIN U19 [get_ports {Result[2]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {Result[2]}]
set_property PACKAGE_PIN V19 [get_ports {Result[3]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {Result[3]}]
set_property PACKAGE_PIN W18 [get_ports {Result[4]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {Result[4]}]
set_property PACKAGE_PIN U15 [get_ports {ALUFlags[0]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {ALUFlags[0]}]
set_property PACKAGE_PIN U14 [get_ports {ALUFlags[1]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {ALUFlags[1]}]
set_property PACKAGE_PIN V14 [get_ports {ALUFlags[2]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {ALUFlags[2]}]
set_property PACKAGE_PIN V13 [get_ports {ALUFlags[3]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {ALUFlags[3]}]
#set_property PACKAGE_PIN V3 [get_ports {led[9]}]                    
#    set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
#set_property PACKAGE_PIN W3 [get_ports {led[10]}]                    
#    set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
#set_property PACKAGE_PIN U3 [get_ports {led[11]}]                    
#    set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
#set_property PACKAGE_PIN P3 [get_ports {led[12]}]                    
#    set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
#set_property PACKAGE_PIN N3 [get_ports {led[13]}]                    
#    set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
#set_property PACKAGE_PIN P1 [get_ports {led[14]}]                    
#    set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
#set_property PACKAGE_PIN L1 [get_ports {led[15]}]                    
#    set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]